
sudo: required
dist: trusty
language: ruby
rvm:
  - 2.5.3
  - 2.3.1

before_install:
  - gem install bundler -v '~> 1.0'

install: ./ci/build.sh

addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev

script: ./ci/test.sh

matrix:
  include:
    - rvm: '2.5.3'
      env:
      - RAILS_VERSION=6.0.0
      - RAILS_VERSION=5.2.0
    - rvm: '2.3.5'
      env:
      - RAILS_VERSION=4.2.0
      - RAILS_VERSION=3.3.2.2

jobs:
  include:
    - stage: publish components
      script: 'cd rswag-api'
      deploy:
        gemspec: rswag-api.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-specs'
      deploy:
        gemspec: rswag-specs.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true

    - stage: publish components
      script: 'cd rswag-ui'
      deploy:
        gemspec: rswag-ui.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        skip_cleanup: true
        on:
          branch: master
          tags: true

    - stage: publish rswag
      script: 'cd rswag'
      deploy:
        gemspec: rswag.gemspec
        provider: rubygems
        api_key: $RUBYGEMS_API_KEY
        on:
          branch: master
          tags: true
