
sudo: required
dist: trusty
language: ruby
rvm:
  - 2.3.1

notifications:
  email: false

before_install:
  - gem install bundler -v '~> 1.0'

install: ./ci/build.sh

env:
  - RAILS_VERSION=5.2.0
  - RAILS_VERSION=4.2.0
  - RAILS_VERSION=3.2.22

addons:
  apt:
    sources:
      - ubuntu-sdk-team
    packages:
      - libqt5webkit5-dev
      - qtdeclarative5-dev

script: ./ci/test.sh

